function [Mg, Ms, R, time] = clump_evolution_exact2(alpha, eps, eta1, mu, etas, td_tff, tmig_td, fg_i)

eta = [0:0.1:10];
mgf = eta;
msf = eta;
mbf = eta;
fgf = eta;
timef = eta;

for i=1:length(eta)
    [T,Y]=ode45(@(t,y)clump_evolution_exact(t, y, alpha, eta(i), eps, mu, etas, td_tff, tmig_td),[0 300],[fg_i 1-fg_i 1]);

    Mg = Y(:,1);
    Ms = Y(:,2);
    R = Y(:,3);
    time = T(:,1);
    Mb = Mg + Ms;
    fg = Mg./Mb;
    fs = 1-fg;
    
    b = find(R<0);
    n = b(1);
    mgf(i) = (Mg(n-1) + ( (Mg(n) - Mg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mg(1);
    msf(i) = (Ms(n-1) + ( (Ms(n) - Ms(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Ms(1);
    mbf(i) = (Mb(n-1) + ( (Mb(n) - Mb(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mb(1);
    fgf(i) = (fg(n-1) + ( (fg(n) - fg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./fg(1);
    timef(i) = (time(n-1) + ( (time(n) - time(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./tmig_td;
end

figure1 = figure('PaperType','a4letter','PaperSize',[20.98 29.68]);
set(figure1,'WindowStyle','docked');

% Create axes
axes1 = axes('Parent',figure1,'YTickLabel',{'0.1','1'},...
    'YTick',[0.1 1],...
    'YMinorTick','on',...
    'YScale','log',...
    'XTickLabel',{'0.1','1','10'},...
    'XTick',[0.1 1 10],...
    'XScale','log',...
    'XMinorTick','on',...
    'TickLength',[0.025 0.05],...
    'Position',[0.12 0.12 0.86 0.82],...
    'PlotBoxAspectRatio',[1 1 1],...
    'LineWidth',1.5,...
    'FontSize',16,...
    'FontName','Arial');

xlim(axes1,[0.2 10]);
ylim(axes1,[0.1 5]);
box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('$\eta$','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.5 -0.05 0]);

% Create ylabel
ylabel('final/initial','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[-0.1 0.5 0]);

tit = strcat('$f_{g0}=',num2str(fg_i,'%3.1f'),'\:\:\alpha=',num2str(alpha,'%3.1f'),...
    '\:\:\epsilon_{\rm SF}=',num2str(eps,'%4.2f'),...
    '\:\: t_{\rm d} / t_{\rm ff}=',num2str(td_tff,'%1.0f'),'$');%,...
    %'\:\:z_{i}=',num2str(zi,'%2.0f'),'$');
% Create title
title(tit,'Interpreter','latex','FontSize',20,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.5 1.01 0]);%,'BackgroundColor',[.7 .9 .7]);

l(1)=loglog(eta,mgf,'marker','none','linewidth',2,'color','b',...
    'DisplayName','$M_{\rm g}$');
l(2)=loglog(eta,msf,'marker','none','linewidth',2,'color','r',...
    'DisplayName','$M_{\rm s}$');
l(3)=loglog(eta,mbf,'marker','none','linewidth',2,'color','m',...
    'DisplayName','$M_{\rm b}$');
l(4)=loglog(eta,fgf,'marker','none','linewidth',2,'color','g',...
    'DisplayName','$f_{\rm g}$');
l(5)=loglog(eta,timef,'marker','none','linewidth',2,'color','c',...
    'DisplayName','$t_{\rm mig}$');

legend1=legend(gca,l(1:5));
set(legend1,'Interpreter','latex','EdgeColor',[1 1 1],...
    'Position',[0.224 0.1435 0.1388 0.2847],...
    'FontSize',14,...
    'FontName','Times New Roman');
set(gcf,'renderer','zbuffer')

[T,Y]=ode45(@(t,y)clump_evolution_exact(t, y, alpha, eta1, eps, mu, etas, td_tff, tmig_td),[0 300],[fg_i 1-fg_i 1]);

Mg = Y(:,1);
Ms = Y(:,2);
R = Y(:,3);
time = T(:,1);
Mb = Mg + Ms;
fg = Mg./Mb;
fs = 1-fg;
b = find(R<0);
n = b(1)-1;

figure2 = figure('PaperType','a4letter','PaperSize',[20.98 29.68]);
set(figure2,'WindowStyle','docked');

% Create axes
axes2 = axes('Parent',figure2,'YTickLabel',{'0.1','1'},...
    'YTick',[0.1 1],...
    'YMinorTick','on',...
    'YScale','log',...
    'XTick',[1:10],...
    'XMinorTick','on',...
    'TickLength',[0.025 0.05],...
    'Position',[0.12 0.12 0.86 0.82],...
    'PlotBoxAspectRatio',[1 1 1],...
    'LineWidth',1.5,...
    'FontSize',16,...
    'FontName','Arial');

xlim(axes2,[1 10]);
ylim(axes2,[0.1 5]);
box(axes2,'on');
hold(axes2,'all');

% Create xlabel
xlabel('$t \:/\: t_d$','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.5 -0.05 0]);

% Create ylabel
ylabel('$M\:/\:M_{\rm i}$','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[-0.1 0.5 0]);

tit = strcat('$f_{g0}=',num2str(fg_i,'%3.1f'),'\:\:\alpha=',num2str(alpha,'%3.1f'),...
    '\:\:\eta=',num2str(eta1,'%3.1f'),...
    '\:\:\epsilon_{\rm SF}=',num2str(eps,'%4.2f'),...
    '\:\: t_{\rm d} / t_{\rm ff}=',num2str(td_tff,'%1.0f'),'$');%,...
    %'\:\:z_{i}=',num2str(zi,'%2.0f'),'$');
% Create title
title(tit,'Interpreter','latex','FontSize',20,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.5 1.01 0]);%,'BackgroundColor',[.7 .9 .7]);

l(1)=loglog(time(1:n),Mg(1:n)./Mg(1),'marker','none','linewidth',2,'color','b',...
    'DisplayName','$M_{\rm g}$');
l(2)=loglog(time(1:n),Ms(1:n)./Ms(1),'marker','none','linewidth',2,'color','r',...
    'DisplayName','$M_{\rm s}$');
l(3)=loglog(time(1:n),Mb(1:n)./Mb(1),'marker','none','linewidth',2,'color','m',...
    'DisplayName','$M_{\rm b}$');
l(4)=loglog(time(1:n),fg(1:n)./fg(1),'marker','none','linewidth',2,'color','g',...
    'DisplayName','$f_{\rm g}$');

legend1=legend(gca,l(1:4));
set(legend1,'Interpreter','latex','EdgeColor',[1 1 1],...
    'Position',[0.224 0.1435 0.1388 0.2647],...
    'FontSize',14,...
    'FontName','Times New Roman');