function fig_clump_bathtub(alpha, eps, mu, td_tff, tmig_td, fg_i, tit)

eta = [0:0.1:10];
mgf = zeros(length(eta),2);
msf = zeros(length(eta),2);
mbf = zeros(length(eta),2);
fgf = zeros(length(eta),2);
timef = zeros(length(eta),2);

for i=1:length(eta)
    [T,Y]=ode45(@(t,y)clump_evolution_exact(t, y, alpha, eta(i), eps, mu, 0, td_tff, tmig_td),[0 300],[fg_i 1-fg_i 1]);

    Mg = Y(:,1);
    Ms = Y(:,2);
    R = Y(:,3);
    time = T(:,1);
    Mb = Mg + Ms;
    fg = Mg./Mb;
    fs = 1-fg;
    
    b = find(R<0);
    n = b(1);
    mgf(i,1) = (Mg(n-1) + ( (Mg(n) - Mg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mg(1);
    msf(i,1) = (Ms(n-1) + ( (Ms(n) - Ms(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Ms(1);
    mbf(i,1) = (Mb(n-1) + ( (Mb(n) - Mb(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mb(1);
    fgf(i,1) = (fg(n-1) + ( (fg(n) - fg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./fg(1);
    timef(i,1) = (time(n-1) + ( (time(n) - time(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./tmig_td;    
    
    [T,Y]=ode45(@(t,y)clump_evolution_exact(t, y, alpha, eta(i), eps, mu, mu, td_tff, tmig_td),[0 300],[fg_i 1-fg_i 1]);

    Mg = Y(:,1);
    Ms = Y(:,2);
    R = Y(:,3);
    time = T(:,1);
    Mb = Mg + Ms;
    fg = Mg./Mb;
    fs = 1-fg;
    
    b = find(R<0);
    n = b(1);
    mgf(i,2) = (Mg(n-1) + ( (Mg(n) - Mg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mg(1);
    msf(i,2) = (Ms(n-1) + ( (Ms(n) - Ms(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Ms(1);
    mbf(i,2) = (Mb(n-1) + ( (Mb(n) - Mb(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./Mb(1);
    fgf(i,2) = (fg(n-1) + ( (fg(n) - fg(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./fg(1);
    timef(i,2) = (time(n-1) + ( (time(n) - time(n-1))./(R(n)-R(n-1)) ) .* (-R(n-1)))./tmig_td;
end

figure1 = figure('PaperType','a4letter','PaperSize',[20.98 29.68]);
set(figure1,'WindowStyle','docked');

% Create axes
axes1 = axes('Parent',figure1,'YTickLabel',{'0.1','1'},...
    'YTick',[0.1 1],...
    'YMinorTick','on',...
    'YScale','log',...
    'XTickLabel',{'0.1','1','10'},...
    'XTick',[0.1 1 10],...
    'XScale','log',...
    'XMinorTick','on',...
    'TickLength',[0.025 0.05],...
    'Position',[0.12 0.12 0.86 0.82],...
    'PlotBoxAspectRatio',[1 1 1],...
    'LineWidth',1.5,...
    'FontSize',16,...
    'FontName','Arial');

xlim(axes1,[0.2 10]);
ylim(axes1,[0.1 5]);
box(axes1,'on');
hold(axes1,'all');

xlabel('${\rm mass\:\:loading\:\:factor}\:\:\eta$','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.5 -0.05 0]);
ylabel('${\rm final/initial\:\:clump\:\:property}$','Interpreter','latex','FontSize',24,...
    'FontName','Times New Roman','units','normalized',...
    'position',[-0.08 0.5 0]);
title(tit,'Interpreter','latex','FontSize',20,...
    'FontName','Times New Roman','units','normalized',...
    'position',[0.50 0.90 0]);

l(2)=plot(eta,mgf(:,1),'marker','none','linestyle','-','linewidth',2,'color','b',...
    'DisplayName','$M_{\rm g}$');
l(3)=plot(eta,msf(:,1),'marker','none','linestyle','-','linewidth',2,'color','r',...
    'DisplayName','$M_{\rm s}$');
l(4)=plot(eta,fgf(:,1),'marker','none','linestyle','-','linewidth',4,'color','g',...
    'DisplayName','$f_{\rm g}$');
l(5)=plot(eta,timef(:,1),'marker','none','linestyle','-','linewidth',2,'color','c',...
    'DisplayName','$t_{\rm mig}$');
l(1)=plot(eta,mbf(:,1),'marker','none','linestyle','-','linewidth',4,'color','m',...
    'DisplayName','$M_{\rm b}$');

plot(eta,mgf(:,2),'marker','none','linestyle','--','linewidth',2,'color','b',...
    'DisplayName','$M_{\rm g}$');
plot(eta,msf(:,2),'marker','none','linestyle','--','linewidth',2,'color','r',...
    'DisplayName','$M_{\rm s}$');
plot(eta,fgf(:,2),'marker','none','linestyle','--','linewidth',4,'color','g',...
    'DisplayName','$f_{\rm g}$');
plot(eta,timef(:,2),'marker','none','linestyle','--','linewidth',2,'color','c',...
    'DisplayName','$t_{\rm mig}$');
plot(eta,mbf(:,2),'marker','none','linestyle','--','linewidth',4,'color','m',...
    'DisplayName','$M_{\rm b}$');

annotation(figure1,'textbox',[0.35 0.87 0.10 0.05],...
    'String',strcat('${\rm \epsilon_{d}}=',num2str(eps*td_tff,'%4.2f'),'$'),...
    'FontSize',18,...
    'FontName','Times',...
    'Interpreter','Latex',...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'BackgroundColor',[1 1 1]);
annotation(figure1,'textbox',[0.55 0.87 0.10 0.05],...
    'String',strcat('${\rm \alpha}=',num2str(alpha,'%4.2f'),'$'),...
    'FontSize',18,...
    'FontName','Times',...
    'Interpreter','Latex',...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'BackgroundColor',[1 1 1]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% annotation(figure1,'textbox',[0.485 0.16 0.10 0.05],...
%     'String',strcat('${\rm \mu}=',num2str(mu,'%4.2f'),'$'),...
%     'FontSize',18,...
%     'FontName','Times',...
%     'Interpreter','Latex',...
%     'FitBoxToText','off',...
%     'LineStyle','none',...
%     'BackgroundColor',[1 1 1]);
% annotation(figure1,'textbox',[0.485 0.23 0.10 0.05],...
%     'String',strcat('${\rm f_{g0}}=',num2str(fg_i,'%4.2f'),'$'),...
%     'FontSize',18,...
%     'FontName','Times',...
%     'Interpreter','Latex',...
%     'FitBoxToText','off',...
%     'LineStyle','none',...
%     'BackgroundColor',[1 1 1]);
% 
% leg_pos = [0.224 0.1635 0.1388 0.2847];
% legend1 = legend(gca,l(1:5));
% set(legend1,...
%     'Position',leg_pos,'FontSize',18,...
%     'Interpreter','latex');
% legend boxoff
% 
% x = 0.60:0.01:0.95;
% y = 0.35.*ones(size(x));
% plot(x,y,'marker','none','linestyle','-','color','k','linewidth',2)
% y = 0.25.*ones(size(x));
% plot(x,y,'marker','none','linestyle','--','color','k','linewidth',2)
% 
% annotation(figure1,'textbox',[0.485 0.30 0.10 0.05],...
%     'String','$\eta_{\rm s}=\mu$',...
%     'FontSize',18,...
%     'FontName','Times',...
%     'Interpreter','Latex',...
%     'FitBoxToText','off',...
%     'LineStyle','none',...
%     'BackgroundColor',[1 1 1]);
% annotation(figure1,'textbox',[0.485 0.37 0.10 0.05],...
%     'String','$\eta_{\rm s}=0$',...
%     'FontSize',18,...
%     'FontName','Times',...
%     'Interpreter','Latex',...
%     'FitBoxToText','off',...
%     'LineStyle','none',...
%     'BackgroundColor',[1 1 1]);

set(gcf,'renderer','painters')
