close all
fclose all
m = 1e9;
disc_mass_thresh      = [-m m];
redshift_thresh       = [-m m];
clump_height_thresh   = [-m m];
clump_dist_thresh     = [-m m];
clump_dens_thresh     = [-m m];
norm_dens_thresh      = [-m m];
clump_shape_thresh    = [-m m];
clump_ssfr_thresh     = [-m m];
mass_thresh           = [7 m];
max_mass_thresh       = [-m m];
lifetime_thresh       = [-m m];
norm_lifetime_thresh  = [-m m]; % clump free fall time
norm_lifetime_thresh2 = [-m m]; % disc dynamical time

norm = [1];
type = [7];
mt = [20];
for i=1:length(norm)
    for j=1:length(type)
%         comparative_clump_mass_function(disc2(disc2_common,:), is2(is2_common,:), ...
%             norm_is2(is2_common,:), disc3(disc3_common,:), is3(is3_common,:), ...
%             norm_is3(is3_common,:), norm(i), disc_mass_thresh, redshift_thresh, ...
%             clump_height_thresh, clump_dist_thresh, clump_dens_thresh, norm_dens_thresh, ...
%             clump_shape_thresh, clump_ssfr_thresh, lifetime_thresh, norm_lifetime_thresh, ...
%             norm_lifetime_thresh2, ...
%             type(j), 1, 1)
%         comparative_clump_mass_function(disc2(disc2_common,:), es2(es2_common,:), ...
%             norm_es2(es2_common,:), disc3(disc3_common,:), es3(es3_common,:), ...
%             norm_es3(es3_common,:), norm(i), disc_mass_thresh, redshift_thresh, ...
%             clump_height_thresh, clump_dist_thresh, clump_dens_thresh, norm_dens_thresh, ...
%             clump_shape_thresh, clump_ssfr_thresh, lifetime_thresh, norm_lifetime_thresh, ...
%             norm_lifetime_thresh2, ...
%             type(j), 1, 2)
%         comparative_clump_mass_function(disc2(disc2_common,:), bulge2(bulge2_common,:), ...
%             norm_bulge2(bulge2_common,:), disc3(disc3_common,:), bulge3(bulge3_common,:), ...
%             norm_bulge3(bulge3_common,:), norm(i), disc_mass_thresh, redshift_thresh, ...
%             clump_height_thresh, clump_dist_thresh, clump_dens_thresh, norm_dens_thresh, ...
%             clump_shape_thresh, clump_ssfr_thresh, lifetime_thresh, norm_lifetime_thresh, ...
%             norm_lifetime_thresh2, ...
%             type(j), 1, 3)
    end
end
for i=1:length(norm)
    for j=1:length(type)
        for k=1:length(mt)
            comparative_clump_mass_function_multiplot(is2(is2_common,:),...
                norm_is2(is2_common,:), is3(is3_common,:), norm_is3(is3_common,:),...
                norm(i), disc2(disc2_common,:), disc3(disc3_common,:),...
                clump_dens_thresh, norm_lifetime_thresh, mass_thresh, max_mass_thresh, type(j), 1);
        end
    end
end

clear disc_mass_thresh redshift_thresh clump_height_thresh clump_dist_thresh
clear clump_dens_thresh norm_dens_thresh clump_shape_thresh clump_ssfr_thresh
clear lifetime_thresh norm_lifetime_thresh norm_lifetime_thresh2 
clear norm type i j